Login
wolox-training/ldch-react pull request #16
Opened 2018-11-28 20:58 UTC by Nosoyleon

## Summary
1. Adding Log in Form with redux-form
2. Vaidating form
3. Using react-router-dom for navigation

## Screenshots
![image](https://user-images.githubusercontent.com/44579645/49181681-03089100-f326-11e8-8faa-b8922c808f02.png)

## Trello Card
https://trello.com/c/w6BurH58/9-routing-i-login

2018-11-29 16:25 UTC, BJordi requested changes

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/app/components/Input/index.js
> +      {meta.error && meta.touched && <div className={style.fieldError}>{meta.error}</div>}
Don't use divs to show text. Instead, use text tags like span or h1-h6.

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/app/components/Input/styles.scss
> +.input {
Add an empty line above this one.

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/app/screens/Game/layout.js
> +        <Board squares={current.squares} />
If current is not required, than, it's possible that current has a null or undefined value, right? If that's the case, `current.squares` may fail.

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/app/screens/Login/index.js
> +  submit = vals => {
values?

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/app/screens/Login/index.js
> +  submit = vals => {
We usually call this functions in this way `handleMyFunction`. Example: If the function will be used when clicking, then you can call it `handleClick` and then do something like this `onClick={this.handleClick}`.

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/app/screens/Login/styles.scss
> +
Remove this line.

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/redux/Auth/actions.js
> +    setTimeout(async () => {
Why are you using this setTimeout here? :thinking:

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/redux/Auth/actions.js
> +  logInProcessing: bool => ({
Just a NTH, you can extract this function and the other two below in another object called `privateActionCreators`.

2018-11-29 16:25 UTC, BJordi commented on react/training-project/src/services/AuthService.js
> +    return response.ok ? response.data.token : null;
What we usually do is to just make the call to the API and in the action deal with the response.
```
//Service file
getUserToken: () => api.get('/sessions', { token });

//Actions file
const response = AuthService.getUserToken(token);
if (response.ok) {
  // Do what you have to do with the response.data
} else {
  // Do what you have to do if the response status is different to 2XX
}
```

2018-11-29 16:56 UTC, Nosoyleon commented on react/training-project/src/redux/Auth/actions.js
> +    setTimeout(async () => {
Just emulating a delay in API response 😄

2018-12-04 16:43 UTC, BJordi approved these changes

2018-12-04 16:43 UTC, BJordi commented on react/training-project/src/app/screens/Game/index.js
> +      <Redirect to="/login" />
Have a constants file in the routes folder and add this one there. Do it in another PR.

2018-12-04 16:43 UTC, BJordi commented on react/training-project/src/app/screens/Game/layout.js
> +        <Board squares={current.squares} />
...? :thinking: :eyes:

2018-12-04 16:43 UTC, BJordi commented on react/training-project/src/app/screens/Login/index.js
> +      <Redirect to="/" />
Same I mentioned above.

2018-12-04 16:43 UTC, BJordi commented on react/training-project/src/app/screens/Login/layout.js
> +  form: 'login'
For future projects, if you are going to use many forms, you can add it to a formNames file :wink::ok_hand:

2018-12-04 20:13 UTC, merged